[package]
name = "wen_store_app"
version = "0.1.0"
edition = "2021"
authors = ["Gui Bibeau <g.bibeaulaviolette@gmail.com>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.2"