import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { ConnectButton } from "@wen-tools/react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ConnectButton theme="w3fs" chainId={5} />
      </main>
    </div>
  );
};

export default Home;
